# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(814, 605)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidgetSource = QtWidgets.QTableWidget(Form)
        self.tableWidgetSource.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidgetSource.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetSource.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetSource.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidgetSource.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidgetSource.setRowCount(0)
        self.tableWidgetSource.setColumnCount(2)
        self.tableWidgetSource.setObjectName("tableWidgetSource")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSource.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSource.setHorizontalHeaderItem(1, item)
        self.tableWidgetSource.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetSource.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.tableWidgetSource)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButtonOpen = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOpen.sizePolicy().hasHeightForWidth())
        self.pushButtonOpen.setSizePolicy(sizePolicy)
        self.pushButtonOpen.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtonOpen.setObjectName("pushButtonOpen")
        self.verticalLayout.addWidget(self.pushButtonOpen)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.lineEditPostfix = QtWidgets.QLineEdit(Form)
        self.lineEditPostfix.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPostfix.sizePolicy().hasHeightForWidth())
        self.lineEditPostfix.setSizePolicy(sizePolicy)
        self.lineEditPostfix.setObjectName("lineEditPostfix")
        self.verticalLayout.addWidget(self.lineEditPostfix)
        self.pushButtonAdd = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.verticalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonDel = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDel.sizePolicy().hasHeightForWidth())
        self.pushButtonDel.setSizePolicy(sizePolicy)
        self.pushButtonDel.setObjectName("pushButtonDel")
        self.verticalLayout.addWidget(self.pushButtonDel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tableWidgetDest = QtWidgets.QTableWidget(Form)
        self.tableWidgetDest.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidgetDest.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetDest.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetDest.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidgetDest.setRowCount(0)
        self.tableWidgetDest.setColumnCount(2)
        self.tableWidgetDest.setObjectName("tableWidgetDest")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDest.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDest.setHorizontalHeaderItem(1, item)
        self.tableWidgetDest.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetDest.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tableWidgetDest)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEditShow = QtWidgets.QTextEdit(Form)
        self.textEditShow.setObjectName("textEditShow")
        self.horizontalLayout_2.addWidget(self.textEditShow)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonOpenXml = QtWidgets.QPushButton(Form)
        self.pushButtonOpenXml.setObjectName("pushButtonOpenXml")
        self.verticalLayout_2.addWidget(self.pushButtonOpenXml)
        self.comboBoxSelSecXml = QtWidgets.QComboBox(Form)
        self.comboBoxSelSecXml.setObjectName("comboBoxSelSecXml")
        self.verticalLayout_2.addWidget(self.comboBoxSelSecXml)
        self.pushButtonGenXml = QtWidgets.QPushButton(Form)
        self.pushButtonGenXml.setObjectName("pushButtonGenXml")
        self.verticalLayout_2.addWidget(self.pushButtonGenXml)
        self.pushButtonSaveXml = QtWidgets.QPushButton(Form)
        self.pushButtonSaveXml.setObjectName("pushButtonSaveXml")
        self.verticalLayout_2.addWidget(self.pushButtonSaveXml)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.pushButtonOpen.clicked.connect(Form.openPatchFiles)
        self.lineEditPostfix.textChanged['QString'].connect(Form.changePostfix)
        self.pushButtonAdd.clicked.connect(Form.addSelectFunctions)
        self.pushButtonDel.clicked.connect(Form.delSelectFunctions)
        self.tableWidgetSource.cellChanged['int','int'].connect(Form.setLineEditText)
        self.tableWidgetSource.cellDoubleClicked['int','int'].connect(Form.addSelectFunctions)
        self.tableWidgetDest.cellDoubleClicked['int','int'].connect(Form.delSelectFunctions)
        self.pushButtonOpenXml.clicked.connect(Form.openXmlFile)
        self.comboBoxSelSecXml.currentTextChanged['QString'].connect(Form.selXmlSection)
        self.pushButtonGenXml.clicked.connect(Form.genXmlText)
        self.pushButtonSaveXml.clicked.connect(Form.saveXmlFile)
        self.tableWidgetSource.cellChanged['int','int'].connect(self.tableWidgetSource.resizeColumnToContents)
        self.tableWidgetDest.cellChanged['int','int'].connect(self.tableWidgetDest.resizeColumnToContents)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "xmlgen"))
        item = self.tableWidgetSource.horizontalHeaderItem(0)
        item.setText(_translate("Form", "File name"))
        item = self.tableWidgetSource.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Function name"))
        self.pushButtonOpen.setText(_translate("Form", "Open"))
        self.pushButtonAdd.setText(_translate("Form", ">>"))
        self.pushButtonDel.setText(_translate("Form", "<<"))
        item = self.tableWidgetDest.horizontalHeaderItem(0)
        item.setText(_translate("Form", "File name"))
        item = self.tableWidgetDest.horizontalHeaderItem(1)
        item.setText(_translate("Form", "New function name"))
        self.pushButtonOpenXml.setText(_translate("Form", "OpenXml"))
        self.pushButtonGenXml.setText(_translate("Form", "Generate"))
        self.pushButtonSaveXml.setText(_translate("Form", "Save"))

